baseURL = "/"
languageCode = "en-us"
title = "Gable's Blog"
theme = "kube"
Paginate = 4
[Params]
  RSSLink = "/index.xml"
  author = "gableh" # add your company name
  github = "gableh" # add your github profile name
  twitter = "" # add your twitter profile
  email = "me@gableh.com"

[[menu.main]]
    name = "Posts"
    weight = -101
    url = "/posts/"
[[menu.main]]
    name = "About me"
    weight = -100
    url = "/about/"
