apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-deployment
  labels:
    app: blog
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blog
  template:
    metadata:
      labels:
        app: blog
    spec:
      containers:
      - name: blog
        image: gableh/hugo:1.0.3
        ports:
        - containerPort: 1313
        env:
          - name: GIT_REPO
            value: "https://github.com/gableh/blog.git"
          - name: BLOG_DIR
            value: "blog"


